name: build-and-test
description: rust build-and-tester
runs:
  using: "composite"
  steps:
    - run: "RUST_LOG=debug cargo build"
    - run: "RUST_LOG=debug cargo test --workspace --all-features -- --nocapture"
