name: build-and-test
description: rust build-and-tester
runs:
  using: "composite"
  steps:
    - name: Build
      run: "RUST_LOG=debug cargo build"
      shell: bash
    - name: Test
      run: "RUST_LOG=debug cargo test --workspace --all-features -- --nocapture"
      shell: bash
